### ISSUE TITLE
`mouseenter` will happen on `document` and error

### ISSUE THREAD

**Issue by fregante** [fregante/delegate-it#20]
```js
delegate(document, '.rgh-table-input-cell', 'mouseenter', console.log, {capture: true});
```

`event.target` happens to be `document` here in some cases, so this line errors because there's no `document.closest`

https://github.com/fregante/delegate-it/blob/66e5cc207c2dd864ce06ff9f7e70a39a98951b89/index.ts#L86

Needs to be investigated a little but I think that it should just be changed to `closest?.()`

--- 

`document` can never be selected by `delegate-it` because it matches no selector, so ignoring it is the right solution.

**Comment by fregante** [comment]
Alternative, actually even better, would be to replace `document` and `window` with `document.documentElement` _before_ attaching the listener, so this never happens.

**Comment by yakov116** [comment]
Off-Topic!
This console error is driving me nuts! had to disable the feature.

I think I should see a doctor seems like I have `console-itis`

**Comment by fregante** [comment]
In v2.0.1
