### ISSUE TITLE
Use abort controllers to remove events

### ISSUE THREAD

**Issue by fregante** [fregante/delegate-it#26]
Either internally or just for the public API, it could support abort controllers instead of returning `.destroy()`

https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener#add_an_abortable_listener

Examples for the public API:

```js
// User-defined controller
const controller = new AbortController();
delegate(document, 'a', 'click', handler, {signal: controller.signal});
controller.abort();
```

```js
// Always create a controller instead of `.destroy()`
const controller = delegate(document, 'a', 'click', handler);
controller.abort();
```

Unfortunately, Safari does not support the signal natively on `addEventListener`, so internally it should keep using `removeEventListener`

**Comment by muescha** [comment]
AbortSignal on Safari:

- there is a polyfill available https://github.com/mysticatea/event-target-shim - but i think this introduces many overhead and unknown code

- the second way would be: if the code runs on Safari and signal not available then add an event listener to signal:

```
signal.addEventListener('abort', () => { 
	delegateSubscription.destroy(); 
   // maybe remove the listener or run it once?
};

signal.addEventListener('abort', delegateSubscription.destroy); 
```

see [AbortSignal:abort_event](https://developer.mozilla.org/en-US/docs/Web/API/AbortSignal/abort_event)

**Comment by fregante** [comment]
AbortController has been in Safari since 12.1, so no polyfill is needed.

**Comment by muescha** [comment]
but at the `AddEventListener` the `option.signal` is not implemented :(

https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener#browser_compatibility

**Comment by fregante** [comment]
Ugh you're right. We can follow your suggestion: instead of passing `signal` to `addEventListener`, we use this locally:

```js
signal.addEventListener('abort', () => {
	base.removeEventListener(blah blah)
});
```

**Comment by fregante** [comment]
> but at the `AddEventListener` the `option.signal` is not implemented :(

It's Safari 15+, it's good enough for me, this will be a breaking release anyway 👍

**Comment by cheap-glitch** [comment]
I've implemented this, but I can't update the tests because JSDOM doesn't support `AbortSignal` in `addEventListener` yet: https://github.com/jsdom/jsdom/issues/3327. I guess I'll take a stab at it
