### ISSUE TITLE
Add support for `{once: true}`

### ISSUE THREAD

**Issue by fregante** [fregante/delegate-it#30]
https://github.com/fregante/delegate-it/blob/719e8347358e000c4b4910598d0fe7641bccb009/index.ts#L117-L118

**Comment by stof** [comment]
Even if you support it in the delegate-it API, you will still probably need to drop it from the native listener options due to sharing the native listener (see the ledger system)

**Comment by fregante** [comment]
Most definitely, even regardless of ledger, our listener is called many times so with `once: true` it would be removed before finding the target

https://github.com/fregante/delegate-it/blob/00b85c8580902c0826a61c21ba1729446422a57b/index.ts#L153
