### ISSUE TITLE
Accept array of selectors

### ISSUE THREAD

**Issue by fregante** [fregante/delegate-it#35]
See https://github.com/fregante/select-dom/blob/93c48807aa37333a1b89c962f19863f151a3aade/index.ts#L19

```js
const selectors = ['a', 'button'];
delegate(document, selectors, 'click', handler)
```

**Comment by GregOriol** [comment]
@fregante You probably should use multiple selectors in the selector string, separated by comma; would be more standard?

**Comment by fregante** [comment]
Yes, but arrays allow you to comment on each selector separately, if necessary. You can still use `'a,button'` as always.
