### ISSUE TITLE
The library reports a type error with Typescript 5.4

### ISSUE THREAD

**Issue by stof** [fregante/delegate-it#50]
`Type 'ParseSelector<Selector, HTMLElement>' does not satisfy the constraint 'Element'`

This seems similar to https://github.com/g-plane/typed-query-selector/issues/35

**Comment by fregante** [comment]
Do you just need to update the underlying type library? What does `npm la typed-query-selector` say? If it's not the latest version, uninstall delegate-it and reinstall it

**Comment by fregante** [comment]
It looks like this package still uses an old version of typed-query-selector. Do you mind sending a PR to update it?
